### ISSUE TITLE
Define license

### ISSUE THREAD

**Issue by lubien** [vuejs-norte/puto-framework#1]

**Comment by iagocavalcante** [comment]
MIT sounds great for this project!

**Comment by lubien** [comment]
Lgtm too

**Comment by thauska** [comment]
Added

**Comment by TiagoDanin** [comment]
+1 MIT

**Comment by lubien** [comment]
@rsomlette please comment here so I can assign you

**Comment by rsomlette** [comment]
@lubien i’ll add the license.md file tomorrow morning if that’s alright.

**Comment by lubien** [comment]
No problem @rsomlette take your time

Just wanted to you to comment here so I could do this:

![image](https://user-images.githubusercontent.com/9121359/66354992-f937bd00-e93c-11e9-90ae-5363f87b3af0.png)
