### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by lubien** [vuejs-norte/puto-framework#10]
- "Puto" means angry in portuguese and it's a curse word!
- This is a framework for HTML not CSS!
- No CSS allowed!
- This is a VueJS framework.

With that in mind, we need a logo :)

**Comment by mandyellow** [comment]
Olá, segue minha sugestão de logo 🦊 Fiz em duas cores, uma mais putão e outra seguindo a paleta do VueJS.

![image](https://user-images.githubusercontent.com/30158643/66160549-0ac64f80-e633-11e9-83ae-9687166d6df6.png)

**Comment by lubien** [comment]
> Olá, segue minha sugestão de logo 🦊 Fiz em duas cores, uma mais putão e outra seguindo a paleta do VueJS.
> 
> ![image](https://user-images.githubusercontent.com/30158643/66160549-0ac64f80-e633-11e9-83ae-9687166d6df6.png)

A paleta do Vue tá perfeita kkk

Por mim é essa @iagocavalcante

**Comment by iagocavalcante** [comment]
Adorei a verdinha também

**Comment by patrickmonteiro** [comment]
Principalmente pela carinha de mau ficar na parte mais escura.
Perfeito!
